# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "공사 중"
description: # this means to ignore newlines until "email:"
   공사 중입니다 =)
url: "http://solin013.github.io" # the base hostname & protocol for your site
baseurl: ""

#used to display twitter cards
twitter_handle: '@dirkfabisch'

#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: false # true, false (default) #df_logo를 띄울지 결정합니다.

# blog cover
cover: "/assets/images/HS_BIG_.png"

#Blog Setting.
name: 'Sollie'
author: 'Sollie'
author_image: "/assets/images/author.jpg"
email: soline013@gmail.com

#첫 페이지에 보여줄 최근 게시물 수 지정.
# > permalink: /:categories/:title/
paginate:	5
# > aginate_path: /page:num/

main:
  - title: "About"
    url: /about/
  - title: "Categories"
    url: /categories/
  - title: "Tags"
    url: /tags/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

#ETC.
#teaser: cover와 비슷하다.
#avatar: 저자 이미지.
#bio: 저자 소개 요약문.
#location: 저자의 나라.
#links: social과 비슷하다.
#og_image: 오픈그래프 프로토콜. 블로그 글이 링크될 때 적용될 기본 이미지 지정.
#footer: 하단을 설정할 수 있다.
#timezone: 한국이면 서울을 사용한다. "Asia/Seoul"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

  - icon:	github
    url:	https://github.com/soline013
    desc:	My github.
    share_url:
    share_title:
    share_link: