# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "공사 중"
description: # this means to ignore newlines until "email:"
   공사 중입니다 =)
email: soline013@naver.com

#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: false # true, false (default) #df_logo를 띄울지 결정합니다.

# blog cover
cover: "/assets/images/HS_BIG_.png"

name: 'La La Land'
author: 'Sollie'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://solin013.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/soline013
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
